Feature/agrega clase polygon
IslasGECI/geoambiental pull request #11
Opened 2019-07-16 23:04 UTC by efren-cabrera

Implementa la clase polygon

2019-07-17 00:23 UTC, evaristor commented
¿En qué renglón está?

2019-07-17 00:25 UTC, efren-cabrera commented
> ¿En qué renglón está?

@evaristor está en el renglón de implementación

2019-07-17 00:42 UTC, devarops requested changes

2019-07-17 00:42 UTC, evaristor commented on geoambiental/Polygon.py
> +        return self.length_km
¿No crees que le falte un lado? Si defino una línea con tres puntos eso hace dos segmentos de línea, pero si defino un polígono con tres puntos, eso debería hacer tres lados.

2019-07-17 00:42 UTC, evaristor commented on geoambiental/tests/test_Polygon.py
> +        self.p = Polygon([23.05, 20.23], [-118.25, -110.25])
Me parece curioso que se pueda crear un polígono con dos puntos. Yo esperaría que la cantidad mínima de puntos para crear un polígono sea tres.

2019-07-17 00:42 UTC, evaristor commented on geoambiental/Polygon.py
> +        return self.length_m
Como no está en el renglón de pruebas podríamos indicar con un comentario (`TODO`) que hace falta la prueba de este método.

2019-07-17 20:19 UTC, jdavidmacer commented on geoambiental/Polygon.py
> +class Polygon(Line, IGeoReferenceBounded):
No entiendo por qué aquí dice `Line`.

2019-07-26 00:59 UTC, efren-cabrera commented on geoambiental/Polygon.py
> +        return self.length_km
Esto ya quedó resuelto, siempre le pondré el primer vertice. Así no importa si me dan un polígono cerrado o no, si es cerrado no habrá distancia entre el primero y el último y si es abierto se cerrará automáticamente.

2019-07-26 01:01 UTC, efren-cabrera commented on geoambiental/tests/test_Polygon.py
> +        self.p = Polygon([23.05, 20.23], [-118.25, -110.25])
Ya cambié la prueba y ahora se define un polígono de tres vertices, sin embargo, no quise quitar la posibilidad de que se puedan definir polígonos de dos vertices. Esto porque puede ser que cuando saquemos contornos de densidad puede ser que no sean cerrados y nos queden líneas, si podemos definir líneas no tendrémos que manejarlos como casos especiales.

2019-07-26 01:02 UTC, efren-cabrera commented on geoambiental/Polygon.py
> +        return self.length_m
Ya agregué corregí la forma de calcular distancias y ahora se calculan agregando el primer vertice al final de los arreglos.

2019-08-01 19:21 UTC, evaristor commented on setup.py
>          "utm",
¿Tronará con esta última coma?

2019-08-07 23:27 UTC, merged