Feature/implementa clase line
IslasGECI/geoambiental pull request #5
Opened 2019-05-31 00:46 UTC by efren-cabrera

Aquí a gregué la primer versión de la clase Line. Esta tarjeta apenas se encuentra en implementación por lo que no está documentada ni tiene pruebas.

2019-06-03 22:55 UTC, jdavidmacer commented
> Aquí a gregué la primer versión de la clase Line. Esta tarjeta apenas se encuentra en implementación por lo que no está documentada ni tiene pruebas.

2019-06-03 22:55 UTC, jdavidmacer commented
@efren-cabrera , ¿cómo puedo revisar la implementación de esta clase?

2019-06-06 15:36 UTC, davidmacer requested changes
Por favor agrega algunas pruebas para saber cómo funciona esta clase.

2019-06-14 19:25 UTC, closed without merging

2019-06-14 19:43 UTC, efren-cabrera reviewed
Aquí acepté todos tus comentarios, sin embargo, aún faltan muchas dependencias así que cerraré este _pull request_