[Implementación] Feature/agrega funcion operaciones comunes
IslasGECI/geoambiental pull request #8
Opened 2019-06-20 17:44 UTC by efren-cabrera

Aquí agregué las funciones para determinar la distancia entre dos puntos y para determinar si un punto cae dentro de un polígono. Estas funciones son utilizadas por diferentes clases para su funcionamiento interno, sin embargo, es posible usarlas por separado. Actualmente están en la columna de implementación, pero ya pueden agregué algunas pruebas.

2019-06-25 18:49 UTC, devarops requested changes

2019-06-25 18:49 UTC, evaristor commented on geoambiental/operations/in_polygon.py
> +def in_polygon(polygon: IGeoReferenceBounded, geo_reference: IGeoReference):
- Los nombres de variables no deberían ser en español?
- Parece que la interfaz está en orden opuesto a como lo habíamos usado en el pasado
- Los nombres de los argumentos de entrada no son claros

2019-06-25 18:49 UTC, evaristor commented on geoambiental/operations/distance.py
> +def distance_between_points_m(geopoint_from: Point, geopoint_to: Point):
- Los nombres de los argumentos de entrada no deberían ser en español?

2019-06-25 23:40 UTC, efren-cabrera commented on geoambiental/operations/distance.py
> +def distance_between_points_m(geopoint_from: Point, geopoint_to: Point):
Revisé la guía de estilo y me parece que en ningún lado se habla sobre el idioma de los parámetros en las funciones. Ya que estas no se deben considerar como variables yo prefiero que sean en inglés, para que coincidan con el nombre de las funciones.

2019-06-25 23:46 UTC, efren-cabrera commented on geoambiental/operations/in_polygon.py
> +def in_polygon(polygon: IGeoReferenceBounded, geo_reference: IGeoReference):
@evaristor ¿Cuál nombre no se te hace claro? el de `geo_reference` se refiere a cualquier cosa que tenga coordenadas, en teoría puede funcionar con puntos, arreglos de puntos, líneas o polígonos y lo que tienen en común es que cumplen la interfaz `IGeoReference` ¿Se te ocurre algún nombre que incluya a todas?

2019-06-26 17:57 UTC, nepito commented on geoambiental/operations/in_polygon.py
> +def in_polygon(polygon: IGeoReferenceBounded, geo_reference: IGeoReference):
Qué te parece similiar al de MATLAB: `query_geo_reference` en lugar de `geo_reference`?

2019-06-26 18:22 UTC, efren-cabrera commented on geoambiental/operations/in_polygon.py
> +def in_polygon(polygon: IGeoReferenceBounded, geo_reference: IGeoReference):
A mi me agrada ese nombre

2019-06-27 20:00 UTC, devarops requested changes

2019-06-27 20:00 UTC, evaristor commented on geoambiental/tests/test_operations_distance.py
> +
Por favor podrías ordenar el preámbulo (los `import`s) alfabéticamente?

2019-06-27 20:00 UTC, efren-cabrera commented on geoambiental/tests/test_operations_distance.py
> +
@evaristor En este caso no es posible, porque operations depende de que esté definido Point

2019-06-27 22:40 UTC, devarops requested changes

2019-06-27 22:40 UTC, evaristor commented on geoambiental/operations/in_polygon.py
> +def in_polygon(geo_reference: IGeoReference, polygon: IGeoReferenceBounded):
@efren-cabrera: Está bien que no te guste `query_geo_reference`, pero `geo_reference` me parece confuso. El problema con `geo_reference` es que me suena a `geo_referencia` o "referencia geográfica"; me hace suponer que debo escoger la referencia o sistema de coordenadas: `WGS84`, `NAD83`, etc.

Permíteme proponerte alternativas:

- `geo_element` o `geoelement`: Se parece al nombre de [una clase de ArcGIS](https://developers.arcgis.com/qt/latest/cpp/api-reference/esri-arcgisruntime-geoelement.html) que representa algo similar
- `georeferenced_element` o `georeferenced_object`: Más largo pero también más descriptivo
- `geo_data` o `geodata`: Esto me inspira algo similar al _query_ y me deja claro que a esto se le "aplicará" el operador `in_polygon` junto con el argumento `polygon`

¿Te gusta alguna de esas alternativas o prefieres que te ofrezca más opciones?

2019-06-27 22:40 UTC, evaristor commented on geoambiental/tests/test_operations_distance.py
> +import unittest
¿Es posible ordenar alfabéticamente lo siguiente?:

```
import unittest
import json

import numpy as np
```

2019-06-28 00:18 UTC, efren-cabrera commented on geoambiental/operations/in_polygon.py
> +def in_polygon(geo_reference: IGeoReference, polygon: IGeoReferenceBounded):
Me gusta `geo_element`

2019-06-28 00:26 UTC, devarops requested changes

2019-06-28 00:26 UTC, evaristor commented on geoambiental/tests/test_operations_distance.py
> +import numpy as np
¿Por favor podrías poner los primeros tres `import` en orden alfabético?

2019-06-28 00:27 UTC, efren-cabrera commented on geoambiental/tests/test_operations_distance.py
> +import numpy as np
no, la guía de estil pep8 dice que las librerías que no son estándar se deben separar.

2019-06-28 00:28 UTC, evaristor commented on geoambiental/tests/test_operations_distance.py
> +import numpy as np
Un enlace a esa parte del pep8 hubiera estado suave

2019-06-28 00:29 UTC, devarops approved these changes

2019-06-28 00:29 UTC, merged